name: Deploy production website

on:
  push:
    branches: [main]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist --prod --message='PRODUCTION ${{ github.sha }}'
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
