name: Deploy production website

on:
  push:
    branches: [main]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Netlify build plugins
        uses: valueourminds/netlify-cli-action@main
        with:
          command: build
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Publish
        uses: valueourminds/netlify-cli-action@main
        with:
          command: deploy --dir=dist --prod --message=PRODUCTION_${{ github.sha }}
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
